name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable
          cache: true

      - name: Backup app code
        run: cp lib/main.dart /tmp/main.dart

      - name: Create Android project
        run: flutter create --platforms=android --org com.royalcards .
      - name: Get SHA-1
        run: |
         mkdir -p ~/.android
          keytool -genkeypair -v \
         -keystore ~/.android/debug.keystore \
         -storepass android \
         -alias AndroidDebugKey \
         -keypass android \
         -keyalg RSA \
         -keysize 2048 \
         -validity 10000 \
         -dname "CN=Android Debug,O=Android,C=US"

         cd android
          chmod +x gradlew
         ./gradlew signingReport
      - name: Add Firebase config
        run: cp google-services.json android/app/google-services.json

      - name: Restore app code
        run: cp /tmp/main.dart lib/main.dart

      - name: Remove default test
        run: rm -f test/widget_test.dart

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: royal-cards-apk
          path: build/app/outputs/flutter-apk/app-release.apk
